### ISSUE TITLE
Error deploy

### ISSUE THREAD

**Issue by sephirothac** [schklom/Mirror-workflows#32]
Hello, 

Thanks for your work, but there is a problem on the deployment of docker feedropolis here are the logs if needed.

edit: I run the service on an arm64 rpi4

Thanks for your work.

docker-compose.yml
version: '3.4'

services:

  app:
    image: stormworks/feedropolis
    ports:
      - 5680:3000
    user: root
    command: npm run start
    entrypoint: '/app/docker-entrypoint.sh'
    environment:
      - DATABASE_URL=postgres://test:test@db:5432/test
      - BASE_URL=http://xxx.xxx.xx.xxx
      - DEBUG=

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

eedropolis-app_1
exec /app/docker-entrypoint.sh: exec format error

**Comment by sephirothac** [comment]
Thank you for your feedback, a mistake on my part I should have paid more attention to the name of targeted image, I will launch the test.

**Comment by sephirothac** [comment]
Thanks again for your help, everything works.

**Comment by schklom** [comment]
You're welcome :)
