### ISSUE TITLE
Allow timezone selection in app container of ttrss

### ISSUE THREAD

**Issue by mossroy** [schklom/Mirror-workflows#44]
It already works in nginx container, but not in app container.
It should be only about adding the "tzdata" package in app/Dockerfile, and would allow it to handle the "TZ" env var (if it exists)

**Comment by schklom** [comment]
Personally, I only want to use my timezone, so I pass this in my docker-compose.yml
```yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```
I do this to all my containers just in case. I think passing `/etc/timezone` should be enough to solve your problem.

If you need a custom timezone, I suggest you write it in a file e.g.
```bash
echo "Europe/Berlin" > /home/mossroy/ttrss_timezone
```
and mount it in the container to `/etc/timezone`.

If this does not work, ask the dev on https://community.tt-rss.org/ or make your own Dockerfile, I do not want to maintain more than I do.
I think this should work:
```dockerfile
FROM schklom/ttrss_web_nginx

ARG TZ
ENV TZ=${TZ:-Europe/Berlin}
RUN apt-get -y install tzdata
```

I can help set up the build and publishing pipeline with GitHub Actions if you need :P

**Comment by mossroy** [comment]
Thanks for your answer (and sorry for the delay)

I have created the PR https://dev.tt-rss.org/tt-rss/ttrss-docker-compose/pulls/8 for that purpose, that has been merged.
So next version of the image should solve this issue

**Comment by schklom** [comment]
Amazing, I will update my image's instructions on DockerHub!
