### ISSUE TITLE
Allow to use a different DNS name than "app" for ttrss backend container

### ISSUE THREAD

**Issue by mossroy** [schklom/Mirror-workflows#45]
This DNS name is currently hard-coded in web-nginx/nginx.conf

It's a constraint when deploying without docker-compose (I'm doing it with k8s).

A solution might be to read it from an environment variable, see https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119

**Comment by schklom** [comment]
I would love this too, even with docker-compose it is a constraint.
For a general fix, you will have to ask this to the dev of the app on https://community.tt-rss.org/, I am only building it for other architectures, and I am not going to mess with it more than I already am.

I don't think it should be difficult to fix on the Dockerfile and the nginx.conf file, but I do not want the problems that will inevitably come from maintaining this. I already spend enough time maintaining the file-logging part.

You can always do what I do: introduce that change yourself in the Dockerfile, then get GitHub to frequently update it + build it + send it to DockerHub.

**Comment by mossroy** [comment]
Thanks for your answer (and sorry for the delay).

I have created https://dev.tt-rss.org/tt-rss/ttrss-docker-compose/pulls/10 for that

**Comment by schklom** [comment]
You rock, my docker-compose file will be easier to manage. Thanks! :)
