### ISSUE TITLE
Gracefully stopping the updater container sometimes leaves the lock/update_daemon.lock file

### ISSUE THREAD

**Issue by mossroy** [schklom/Mirror-workflows#46]
When the updater container is gracefully stopped, it should remove the lock/update_daemon.lock file, so that another instance of this container can continue the updates.

It's currently not always the case. I suppose it happens when you stop the container during an upgrade.

This happens to me under k8s (when the corresponding pod is gracefully killed by k8s), but the same issue probably affects the updater when run by docker-compose (I did not check)

**Comment by schklom** [comment]
I only maintain a build for architectures that the dev does not support.
This sounds like a problem from the app itself, so I suggest you ask this on the TT-RSS forum directly at https://community.tt-rss.org/, the developer is quite active.

**Comment by mossroy** [comment]
I've opened a thread on the forum for that: https://community.tt-rss.org/t/gracefully-stopping-the-updater-container-sometimes-leaves-the-lock-update-daemon-lock-file/5852
