### ISSUE TITLE
Update Find my device server docker image

### ISSUE THREAD

**Issue by Carontes** [schklom/Mirror-workflows#71]
Hi, is it possible to update to the latest version the FMDserver docker image? The last and only image has 2 years on hub.docker.com, while new versions, on the gitlab page, has been released. Thank you

**Comment by schklom** [comment]
I have tried but the build fails for some reason. I will investigate more when I have time and most likely complain on the FMDserver repository. Feel free to give me some help to figure out what goes wrong :P

**Comment by schklom** [comment]
Works now
