### ISSUE TITLE
FindMyDeviceServer

### ISSUE THREAD

**Issue by kinslayer1982** [schklom/Mirror-workflows#86]
Hi.
What kind of bug is there with the FindMyDeviceServer Branch? I just switched from your Docker image I was using to theirs and everything works (as long as the required changes between the versions are considered).

**Comment by schklom** [comment]
Hi

Thanks for pointing it out, I wouldn't have noticed this myself ^^

I honestly don't remember. I marked it as bugged in [March 2023](https://github.com/schklom/Mirror-workflows/commit/ecea8a06e60970c2acb1a0c861bc0cba6f66bc8c), but I can't remember why, and unfortunately at almost 1AM I was likely too tired to think about documenting the reason :P

I think the author had a bug on his Dockerfile, and I didn't figure out a solution, so I just marked it as bugged in the meantime, then forgot to update when he fixed it.

The author maintains his own image on amd64 & armv7 & arm64 anyway, so mine has no reason to exist anymore.
